name: Build APK

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos

      - name: Build APK arm64-v8a (flagship & mid-range)
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload arm64 APK
        uses: actions/upload-artifact@v4
        with:
          name: marsa-cbt-arm64-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90

      - name: Build APK armeabi-v7a (low-end & jadul)
        run: flutter build apk --release --target-platform android-arm

      - name: Upload armeabi APK
        uses: actions/upload-artifact@v4
        with:
          name: marsa-cbt-arm32-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90